python scripts/Coeff_totxt.py --WCNAME ctj1 > Julia_files_WC_template2/Coeffs/Coeffs_ctj1.py
python scripts/Coeff_totxt.py --WCNAME cQd1 > Julia_files_WC_template2/Coeffs/Coeffs_cQd1.py
python scripts/Coeff_totxt.py --WCNAME cQu1 > Julia_files_WC_template2/Coeffs/Coeffs_cQu1.py
python scripts/Coeff_totxt.py --WCNAME ctj8 > Julia_files_WC_template2/Coeffs/Coeffs_ctj8.py
python scripts/Coeff_totxt.py --WCNAME cQd8 > Julia_files_WC_template2/Coeffs/Coeffs_cQd8.py
python scripts/Coeff_totxt.py --WCNAME cQu8 > Julia_files_WC_template2/Coeffs/Coeffs_cQu8.py
python scripts/Coeff_totxt.py --WCNAME ctd1 > Julia_files_WC_template2/Coeffs/Coeffs_ctd1.py
python scripts/Coeff_totxt.py --WCNAME ctu1 > Julia_files_WC_template2/Coeffs/Coeffs_ctu1.py
python scripts/Coeff_totxt.py --WCNAME cQj11 > Julia_files_WC_template2/Coeffs/Coeffs_cQj11.py
python scripts/Coeff_totxt.py --WCNAME cQj31 > Julia_files_WC_template2/Coeffs/Coeffs_cQj31.py
python scripts/Coeff_totxt.py --WCNAME ctd8 > Julia_files_WC_template2/Coeffs/Coeffs_ctd8.py
python scripts/Coeff_totxt.py --WCNAME ctu8 > Julia_files_WC_template2/Coeffs/Coeffs_ctu8.py
python scripts/Coeff_totxt.py --WCNAME cQj38 > Julia_files_WC_template2/Coeffs/Coeffs_cQj38.py
python scripts/Coeff_totxt.py --WCNAME cQj18 > Julia_files_WC_template2/Coeffs/Coeffs_cQj18.py
python scripts/Coeff_totxt.py --WCNAME ctGIm > Julia_files_WC_template2/Coeffs/Coeffs_ctGIm.py
python scripts/Coeff_totxt.py --WCNAME ctGRe > Julia_files_WC_template2/Coeffs/Coeffs_ctGRe.py
python scripts/Coeff_totxt.py --WCNAME cG > Julia_files_WC_template2/Coeffs/Coeffs_cG.py
